### ISSUE TITLE
Why are circulation pumps node element components?

### ISSUE THREAD

**Issue by dlohmeier** [e2nIEE/pandapipes#372]
**Problem Description**
Circulation pumps inherit from `NodeElementComponent` via `ExtGrid`. However, when looking at my network, this component is clearly a branch component, as it connects two junctions. The behavior leads to errors when calling the `element_junction_tuple` function in the toolbox, as it assumes by default that branch components have entries "from/to_junction" and node elements have entries "junction". So, in my case, I wanted to select a subnet and 

**To Reproduce**
    
    from pandapipes.test.test_toolbox import create_base_net, add_pumps
    from pandapipes.toolbox import element_junction_tuples
    net = create_base_net(True)
    add_pumps(net)
    for table, column in element_junction_tuples(net=net):
    print(table)
    print(net[table][column].values)

**Output with Error message**
valve
[5]
pump
[3]
press_control
[9]
pump
[6]
press_control
[9]
pipe
[0 1 1 2 3 6 6]
heat_exchanger
[7]
pipe
[1 2 3 4 5 7 7]
sink
[3]
ext_grid
[0]
heat_exchanger
[2]
circ_pump_mass

Traceback (most recent call last):
  File "C:\Users\dlohmeier\miniconda3\lib\site-packages\pandas\core\indexes\base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'junction'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\dlohmeier\miniconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3397, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-34-e767f0eaa917>", line 2, in <cell line: 1>
    print(table, net[table][column].values)
  File "C:\Users\dlohmeier\miniconda3\lib\site-packages\pandas\core\frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\dlohmeier\miniconda3\lib\site-packages\pandas\core\indexes\base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'junction'

**Expected behavior**
So, we can see that circ_pump_mass does not have the expected "junction" entry.

**Python environment (please complete the following information):**
 - OS: Windows 10
 - pandapipes version: 0.6.1.dev_0

**Sugestions**
My first workaround will be to make manual changes to the `element_junction_tuples` function, but I think that it would be more concise to make pumps inherit from the `BranchElementComponent` class.

**Comment by dlohmeier** [comment]
The workaround is implemented in PR #370

**Comment by jkisse** [comment]
if this is fixed by #449 , please close the issue @dlohmeier (there is no description in the PR so it is hard to assess from the outside)

**Comment by dlohmeier** [comment]
Yes, it is fixed, thanks for the hint @jkisse !
